### ISSUE TITLE
New plugin Lightbar

### ISSUE THREAD

**Issue by LakiBR** [CallmeBK/VolLightbarCtrlWithDS4#5]
Would it be possible to create a plugin that keeps the DS4 light bar always at minimum (or off)? It would help a lot with saving battery power. Thank you very much in advance.

**Comment by CallmeBK** [comment]
Hi LakiBR,

You should be able to toggle the lightbar to a dim setting by pressing L1, R1, L2, and R2 at the same time. It should remember that setting until you press that same combination of buttons again.

**Comment by LakiBR** [comment]
Sadly this combo doesn't work for me on PSTV. I already tried, and doesn't change a thing. :(

**Comment by CallmeBK** [comment]
Ah I think I might know what the issue is. I'll see if I can make an update to fix that. In the meantime, open up this file in vitashell:

ux0:data/VolLightbarCtrlWithDS4/p1config.txt

and change the number in the text file from a 100 to a 5. Then save and close the text file and restart your vita tv. 

That number represents the brightness percentage for player 1. 100 is full brightness. 5 would be 5 percent brightness which is what I use for the dim setting.

**Comment by LakiBR** [comment]
Thank you for all of your support. Tried to follow your steps, but on PSTV this folder doesn't even exist. On VitaShell the folder VolLightbarCtrlWithDS4 is absent.

**Comment by CallmeBK** [comment]
Oh that's right, whoops. Since the L1, L2, R1, R2 isn't working yet for vita TV, that file was never created.

You can just manually create it then actually.

Ceate this file:

ux0:data/VolLightbarCtrlWithDS4/p1config.txt

and in the text file, just type the number 5. Then save and close the file. And restart vita tv.

If the VolLightbarCtrlWithDS4 folder doesn't exist inside ux0:data, just create that folder manually too. Then you can put a p1config.txt file inside it.

**Comment by LakiBR** [comment]
Done, but nothing changes sadly.

**Comment by CallmeBK** [comment]
I just discussed this with another PS TV user.  This other user does not have any issues with this lightbar brightness toggle functionality.  

1) Could you send me your config.txt file?  There could be another plugin you are using that interferes with this one.
2) You are using an official DS4 controller right?
3) Open that p1config.txt file you created and send me a screenshot of that entire screen

**Comment by LakiBR** [comment]
Man, I'm really sorry. I was using the Autoplugin version, but its outdated. Replaced with the upda.ted version, and works properly. I'm really sorry.

**Comment by LakiBR** [comment]
Thank you for all of your effort.

**Comment by CallmeBK** [comment]
Ooo gotcha gotcha. You're welcome :) Glad you were able to get it working in the end.
